export default function Rarity() {
 return (
  <section
  className="border-x-0 border-t-0 border-b border-b-slate-600 py-12 mx-4 sm:mx-12 text-black dark:text-white  "
  id="rarity"
>
  <div className="flex flex-col items-center">
    <h1 className="text-3xl py-2 font-medium font-serif">Rarity</h1>
    <p className="font-hand text-xl">
      Each NFT is algorithmically generated by combining 110+ unique
      traits with varying rarity across categories:
    </p>
    <ul className="list-disc flex flex-nowrap mx-2 font-hand">
      <li className="mx-4">Body</li>
      <li className="mx-4">Eyes</li>
      <li className="mx-4">Whiskers</li>
      <li className="mx-4">Ears</li>
    </ul>
    <div className="flex lg:flex-row flex-col justify-around mt-3 font-hand">
      <div className="flex flex-wrap flex-col items-center px-3 mt-6 lg:mt-0">
        <div className="w-64 ">
          <img
            alt="..."
            src="/img/fish2.jpg"
            className="object-cover w-full h-full rounded-md"
          />
        </div>

        <p className="text-xl font-medium pt-2"> - Novice Clan -</p>
        <p className="text-gray-500 py-2">Not really common.</p>
        <p className="">Fighting Power - Great</p>
      </div>
      <div className="flex flex-wrap flex-col items-center px-3 mt-6 lg:mt-0">
        <div className="w-64">
          <img
            alt="..."
            src="/img/fish3.jpg"
            className="object-cover w-full h-full rounded-md"
          />
        </div>

        <p className="text-xl font-medium pt-2"> * Expert Clan *</p>
        <p className="text-gray-500 py-1">Very Expert.</p>
        <p className="">Fighting Power - Phenomenal</p>
      </div>
      <div className="flex flex-wrap flex-col items-center px-3 mt-6 lg:mt-0">
        <div className="w-64">
          <img
            alt="..."
            src="/img/fish4.png"
            className="object-cover w-full h-full rounded-md"
          />
        </div>

        <p className="text-xl font-medium pt-2"> *** Legend Clan ***</p>
        <p className="text-gray-500 py-2">Have this and be unbeatable.</p>
        <p className="">Fighting Power - Genius</p>
      </div>
    </div>
  </div>
</section>
 )
}